# Site settings
course_name: Introduction to Computer Music
#course_description:
#"Intro to Computer Music teaches you to program computers to synthesize, process, and understand musical sound, and is taught simultaneously to both undergraduate (322) and graduate (622) sections. This course is both technical and creative—think of it as the musical equivalent to a CS course on computer graphics. Projects will task you to both (i) apply technical skills to create musical tools, (ii) exercise your creativity using those tools. A background in programming is required (15-112 or equivalent at a minimum), but formal training in music is not required.
#This semester's version of the course differs significantly from all previous iterations. In particular, all of the projects and exams have been rewritten to use Python instead of Nyquist (the previous teaching language for the course). Moreover, there is a stronger emphasis on real-time interaction, low-level audio programming, and less emphasis on computer music composition techniques. This is the first iteration of this new version of the course and accordingly, expect things to be rough around the edges at times. We are eager to hear your feedback—you have the opportunity to help shape the future of this course!"
course_semester: "Spring 2025"

baseurl: "/icm-s25" # the subpath of site
url: "https://gclef-cmu.github.io" # the base hostname & protocol for site

schoolname: "Carnegie Mellon University"
schoolurl: "https://www.cmu.edu/"
twitter_username: CarnegieMellon

address: |
  5000 Forbes Ave, 
  Pittsburgh, PA 15213, 
  United States

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ["_images", "_css"]
exclude: ["develop"]

dateformat: "%m/%d/%Y"

future: true
collections:
  events:
    output: true
  lectures:
    output: true
  projects:
    output: true
  announcements:
    output: false

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
